[package]
name = "learn-flash-attn"
version = "0.0.8"
edition = "2024"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
any-tensor = "0.0"
cuda = { git = "https://github.com/YdrMaster/cuda-driver", rev = "c535e9f" }

[build-dependencies]
build-script-cfg = "0.1"
find_cuda_helper = "0.2"

[dev-dependencies]
rand = "0.9"
